<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>buyConfirm</title>
	</head>
	<body>
		<div align="center">
			<h1>書籍管理システム</h1>
			<hr>
			<table width="100%">
				<tr>
					<td align="center" width="10%" rowspan="2"><a href="../menu/menu.php">[メニュー]</a></td>
					<td align="center" width="10%" rowspan="2"><a href="../listBook/listBook.php">[書籍一覧]</a></td>
					<td align="center" width="60%" rowspan="2"><font size="5"><strong>Order Confirmation</strong></font></td>
					<td align="left" width= "15%">名前：<?= $User->getUser()?></td>
					<td width="5%">&nbsp;</td>
				</tr>
				<tr>
					<td align="left" width="15%">権限：<?= $User->getAuthority() ?></td>
				</tr>
			</table>
			<hr>
			<br>
			<?php
			if($cartInfo){
			?>
			<table width="80%">
				<tr>
					<th>下記の書籍を購入いたしました。</th>
				</tr>
				<tr>
					<th>ご購入ありがとうございました。</th>
				</tr>
			</table>
			<br>
			<table width="80%">
				<tr>
					<th align="center" width="20%" bgcolor="#dcdcdc">ISBN</th>
					<th align="center" width="20%" bgcolor="#dcdcdc">TITLE</th>
					<th align="center" width="20%" bgcolor="#dcdcdc">PRICE</th>
					<th align="center" width="10%" bgcolor="#dcdcdc">Quantity</th>
					<th align="center" width="10%" bgcolor="#dcdcdc">Sub-Total</th>
				</tr>
				<?php
				foreach($cartInfo as $order){
				    $sub_total = (int)$order->getPrice() * (int)$order->getQuantity();
				?>
				<tr>
					<td align="center" width="20%"><?= $order->getIsbn() ?></td>
					<td align="center" width="20%"><?= $order->getTitle() ?></td>
					<td align="center" width="20%"><?= $order->getPrice() ?></td>
					<td align="center" width="10%"><?= $order->getQuantity() ?>冊</td>
					<td align="center" width="10%"><?= $sub_total  ?>円</td>
				</tr>
				<?php
				$total += $sub_total;
				}
				?>
			</table>
			<br>
			<br>
			<br>
			<hr style="double">
			<table width="80%">
				<tr>
					<th align="center" width="60%">&nbsp;</th>
					<th align="center" width="10%" bgcolor="#dcdcdc">Total</th>
					<td align="center" width="10%"><?= $total ?>円</td>
				</tr>
			</table>
			<?php
			}else{
			?>
			<p><strong>購入された商品はありません。</strong>
			<?php
			}
			?>
		</div>
	</body>
</html>