<?php
//セッションの開始
session_start();

//権限の判別
if($_SESSION['userInfo']['authority'] == 1){
    $authority = "一般ユーザー";
}else{
    $authority = "管理者";
}

//書籍情報を取得
$book = $model->getBookInfo();

?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Update</title>
	</head>
    <body>
		<h1 align="center" color="red">書籍管理システム</h1>
		<hr align="center" size="5" color="red" width="100%">
		<table width="100%">
			<tr>
				<td width="11%"><a href="../menu/menu.php"></a></td>
				<td width="11%"><a href="../insertBook/insertBook.php"></a></td>
				<td width="11%"><a href="../listBook/listBook.php"></a></td>
				<td align="center" width="34%"><h2>MENU</h2></td>
				<td width="33%">
					<table align="right">
						<tr>
							<td>名前：<?=$_SESSION['userInfo']['user']?></td>
						</tr>
						<tr>
							<td>権限：<?=$authority?></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<hr align="center" size="2" color="red" width="100%">
		<br><br>
		<form action="updateBook.php" method="post">
			<table align="center" width="55%">
				<tr>
					<td align="left" width="15%"></td>
					<td align="center" width="20%">＜変更前情報＞</td>
					<td align="center" width="20%">＜変更後情報＞</td>
				</tr>
				<tr>
					<th align="left" width="15%" bgcolor="6666FF">　ISBN</th>
					<td align="left" width="20%"><?=$book['isbn']?></td>
					<td align="left" width="20%"><?=$book['isbn']?><input type="hidden" name="isbn" value="<?=$book['isbn']?>"></td>

				</tr>

				<tr>
					<th align="left" width="15%" bgcolor="6666FF">　TITLE</th>
					<td align="left" width="20%"><?=$book['title']?></td>
				<?php
                if($model->getExecute()==null){
                ?>
					<td align="left" width="20%" ><input type=text size="30" name="title" value="<?=$book['title']?>"></input></td>
				<?php
				}else{
                ?>
					<td align="left" width="20%" ><?=$model->getTitle()?></td>
				<?php
				}
                ?>
				</tr>
				<tr>
					<th align="left" width="15%" bgcolor="#6666FF">　価格</th>
					<td align="left" width="20%"><?=$book['price']?>円</td>
				<?php
                if($model->getExecute()==null){
                ?>
					<td align="left" width="20%" ><input type=text size="30" name="price" value="<?=$book['price']?>"></input></td>
				<?php
				}else{
                ?>
					<td align="left" width="20%" ><?=$model->getPrice()?></td>
				<?php
			    }
                ?>
				</tr>
			</table>
			<?php
            if($model->getExecute()==null){
            ?>
<!-- 				<input type="hidden" name="execute" value="update"> -->
				<p align="center"><input type="submit" name="execute" value="変更完了"></input></p>
			<?php
		    }else{
            ?>
				<p align="center"><font size="4">上記内容でデータを更新しました。</font></p>
				<p align="center"><a href="../listBook/listBook.php">書籍一覧へ戻る</a></p>
			<?php
		    }
            ?>
	</form>
	<br><br><br>
	<hr align="center" size="2" color="red" width="100%">
	<table align="center" width="100%">
		<tr><td>Copyright (C) 2022 All Rights Reserved.</td></tr>
	</table>
	</body>
</html>