<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<title>Login</title>
	</head>
	<body>
		<div align="center">
    		<h1>書籍管理システム</h1>
    		<hr>
    		<h2>Login</h2>
    		<hr>
    		<br>
    		<br>
    		<?php if(isset($_POST['login']) && isset($result)){?>
    			<p><font color="red"><strong><?= $result?></strong></font></p>
    		<?php }?>
    		<form action="login.php" method="post">
        		<table>
        			<tr>
        				<th>User</th>
        				<td><input type="text" name="user"></td>
        			</tr>
        			<tr>
        				<th>Password</th>
        				<td><input type="password" name="password"></td>
        			</tr>
        		</table>
        		<br>
        		<br>
        		<input type="submit" name="login" value="LOGIN">
    		</form>
    	</div>
	</body>
</html>