<?php
//セッションの開始
session_start();

//権限の判別
if($_SESSION['userInfo']['authority'] == 1){
    $authority = "一般ユーザー";
}else{
    $authority = "管理者";
}
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Insert title here</title>
	</head>
    <body>
    <h1 align="center" color="green">書籍管理システム</h1>
		<hr align="center" size="3" color="green" width="100%">
		<table width="100%">
			<tr>
				<td width="33%">[<a href="../menu/menu.php">メニュー</a>]　　
								[<a href="../listBook/listBook.php">書籍一覧</a>]</td>
				<td align="center" width="34%">
				<font color ="#800000" size="3"><h2>書籍詳細情報</h2></font></td>
				<td width="33%">
					<table align="right">
						<tr>
							<td>名前：<?=$_SESSION['userInfo']['user']?></td>
						</tr>
						<tr>
							<td>権限：<?=$authority?></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<hr align="center" size="1" color="green" width="100%">
		<br><br>

		<?php
		if($authority == "一般ユーザー"){	// 一般ユーザー
		?>
		<br><br><br>
		<div align="center">
        	<form action="../insertIntoCart/insertIntoCart.php" method="post">
        		<input type="text" name="quantity" style="width: 100px;" placeholder="Quantity">
        		<input type="submit" name="insertIntoCart" value="insertIntoCart">

        	</form>
		</div>

	<?php
		}else{
		?>

		<div align="center">
		<table border="0">
		<!-- 変更ボタン -->
		<td><form action="../deleteBook/deleteBook.php" method="post">
			<input type="hidden" name="isbn" value="<?=$_POST['isbn']?>">
			<input type="submit" name="kekka" value="削除">
		</form>
		</td>
		<td>&emsp;</td>
		<!-- 削除ボタン -->
		<td><form action="../updateBook/updateBook.php" method="post">
			<input type="hidden" name="isbn" value="<?=$_POST['isbn']?>">
			<input type="submit" name="updateBook" value="変更">
			</form>
		</td>
		</table>
		</div>

	<br><br>


		<?php
		}
		?>


<!-- 		<form action="listBook.php" method="post"> -->
	<!-- Common -->
    <table align="center" border="0">
    <tr>
    <th bgcolor="#DDDDDD" width="200">ISBN</th>
    <td bgcolor="#CCFFCC" width="200"><?=$book->getIsbn()?></td>
			</tr>

			<tr>
				<th bgcolor="#DDDDDD" width="200">TITLE</th>
				<td bgcolor="#CCFFCC" width="200"><?=$book->getTitle()?></td>
			</tr>

			<tr>
				<th bgcolor="#DDDDDD" width="200">価格</th>
				<td bgcolor="#CCFFCC" width="200"><?=$book->getPrice()?>円</td>
			</tr>


	</table>
<!-- 	</form> -->



	<br><br><br><br><br><br><br><br><br><br><br>

		<hr align="center" size="1" color="green" width="100%">
		<table align="center" width="100%">
			<tr><td>Copyright (C) 2022 All Rights Reserved.</td></tr>
		</table>

    </body>
</html>
