<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>changePassword</title>
		<style>
		  table{
		      width: 600px;
		      margin: auto;
		      text-align: center;
		  }
		  body{
		      text-align: center;
		      width: 900px;
		      margin: auto;
		  }
		  th {
		       background-color: #b5e9ff; /* 赤に合うように色変えてみたよ    */
		       width: 200px;
		  }
		   header{
            display: flex;
            align-items: center;
           }
           header p { flex: 1;}
           header h3 { flex: auto; text-align: center; }
           nav {
             flex: 1;
             width: 200px;
           }
           nav ul {
        	list-style: none;
        	margin: 0;
        	padding: 0;
        	display: flex;
           }
           nav a {
            width: 100px;
            text-decoration: none;
            text-align: center;
            line-height: 65px;
            display: block;
           }
		</style>
	</head>
    <body>
    	<!-- header -->
    	<h1 align="center">書籍管理システム3.0版（シムテック）</h1>
    	<hr color="red">
    	<header>
    		<nav>
    			<ul>
    				<li><a href="../menu/menu.php">メニュー</a></li>
    				<li><a href="../listUser/listUser.php">ユーザー一覧</a></li>
    			</ul>
    		</nav>
    		<h3>ユーザー詳細</h3>
    		<p>名前：<?=$_SESSION['userInfo']['user']?><br>
    		   権利：<?=$searchObj->changeString($_SESSION['userInfo']['authority'])?></p>
    	</header>
    	<hr color="red" style="margin-bottom: 20px;">

    	<?php if($result === true){?>
    		更新成功！
    	<?php }else{ echo $result;?>
    	<form action="changePassword.php" method="post">
    		<table>
    			<tr>
    				<th></th>
    				<th width="200">更新前</th>
    				<th width="200">更新後</th>
    			</tr>
    			<tr>
    				<td bgcolor="#69a1fa">Userid</td>
    				<td><?=$_SESSION['userInfo']['user']?></td>
    				<td><?=$_SESSION['userInfo']['user']?></td>
    			</tr>
    			<tr>
    				<td bgcolor="#69a1fa">Pass</td>
    				<td><?=$_SESSION['userInfo']['password']?></td>
    				<td><input type="password" name="old"></td>
    			</tr>
    			<tr>
    				<td bgcolor="#69a1fa">newPass</td>
    				<td></td>
    				<td><input type="password" name="new1"></td>
    			</tr>
    			<tr>
    				<td bgcolor="#69a1fa">確認</td>
    				<td></td>
    				<td><input type="password" name="new2"></td>
    			</tr>
    		</table>
    		<input type="submit" value="パスワード変更" name="change">
    		<input type="hidden" name="userid" value="<?=$_SESSION['userInfo']['user']?>">
    	</form>
    	<?php }?>

    	<!-- footer -->
		<footer style="bottom: 0; position: absolute;">
		<hr color="red" width="900">
		Copyright (C) 2022 All Rights Reserved.
		</footer>
    </body>
</html>