<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>insertIntoCart</title>
	</head>
	<body>
		<div align="center">
			<h1>書籍管理システム</h1>
			<hr>
			<table width="100%">
				<tr>
					<td align="center" width="10%" rowspan="2"><a href="../menu/menu.php">[メニュー]</a></td>
					<td align="center" width="10%" rowspan="2"><a href="../listBook/listBook.php">[書籍一覧]</a></td>
					<td align="center" width="60%" rowspan="2"><font size="5"><strong>Insert Into Cart</strong></font></td>
					<td align="left" width= "15%">名前：<?= $user->getUser()?></td>
					<td width="5%">&nbsp;</td>
				</tr>
				<tr>
					<td align="left" width="15%">権限：<?= $user->getAuthority() ?></td>
				</tr>
			</table>
			<hr>
			<br>
			<br>
			<p><font size="4"><strong>下記の書籍データをカートに追加しました。</strong></font>
			<br>
			<table width="20%">
				<tr>
					<th align="left" width="10%" bgcolor="#dcdcdc">&nbsp;ISBN</th>
					<td align="left" width="10%">&nbsp;<?= $cart->getIsbn() ?></td>
				</tr>
				<tr>
					<th align="left" width="10%" bgcolor="#dcdcdc">&nbsp;Title</th>
					<td align="left" width="10%">&nbsp;<?= $cart->getTitle() ?></td>
				</tr>
				<tr>
					<th align="left" width="10%" bgcolor="#dcdcdc">&nbsp;Price</th>
					<td align="left" width="10%">&nbsp;<?= $cart->getPrice() ?></td>
				</tr>
				<tr>
					<th align="left" width="10%" bgcolor="#dcdcdc">&nbsp;Quantity</th>
					<td align="left" width="10%">&nbsp;<?= $cart->getQuantity() ?></td>
				</tr>
			</table>
			<br>
			<br>
			<br>
			<p><a href="../showCart/showCart.php">[カート一覧へ]</a></p>
		</div>
	</body>
</html>