<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>buyConfirm</title>
	</head>
	<body>
		<div align="center">
			<h1>書籍管理システム</h1>
			<hr>
			<table width="100%">
				<tr>
					<td align="center" width="10%" rowspan="2"><a href="../menu/menu.php">[メニュー]</a></td>
					<td align="center" width="10%" rowspan="2">&nbsp;</td>
					<td align="center" width="60%" rowspan="2"><font size="5"><strong>Insert Initial Data</strong></font></td>
					<td align="left" width= "15%">名前：<?= $User->getUser()?></td>
					<td width="5%">&nbsp;</td>
				</tr>
				<tr>
					<td align="left" width="15%">権限：<?= $User->getAuthority() ?></td>
				</tr>
			</table>
			<hr>
			<br>
			<?php
				if(isset($booklist)){
			?>
			<p widht="60%"><font size="4"><strong>書籍データとして下記のデータを登録しました。</strong></font></p>
			<br>
			<table width="60%">
				<tr>
					<th align="center" width="20%" bgcolor="#dcdcdc">ISBN</th>
					<th align="center" width="20%" bgcolor="#dcdcdc">TITLE</th>
					<th align="center" width="20%" bgcolor="#dcdcdc">PRICE</th>
				</tr>

				<?php
				    foreach($booklist as $book){
				?>
				<tr>
					<td align="center" width="20%"><?= $book->getIsbn() ?></td>
					<td align="center" width="20%"><?= $book->getTitle() ?></td>
					<td align="center" width="20%"><?= $book->getPrice() ?>円</td>
				</tr>
				<?php
				    }

				?>

			</table>
			<?php
				}else{
			?>
				<p>初期データ登録できてないで</p>
			<?php
				}
			?>
		</div>
	</body>
</html>