<?php
//セッションの開始
session_start();

//権限の判別
if($_SESSION['userInfo']['authority'] == 1){
    $authority = "一般ユーザー";
}else{
    $authority = "管理者";
}


?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>DetailUser</title>
	</head>
    <body>
    <h1 align="center" color="red">書籍管理システム</h1>
		<hr align="center" size="3" color="red" width="100%">
		<table width="100%">
			<tr>
				<td width="33%">[<a href="../menu/menu.php">メニュー</a>]　　
								[<a href="../listUser/listUser.php">ユーザー一覧</a>]</td>
				<td align="center" width="34%">
				<font color ="#800000" size="3"><h2>ユーザー詳細情報</h2></font></td>
				<td width="33%">
					<table align="right">
						<tr>
							<td>名前：<?=$_SESSION['userInfo']['user']?></td>
						</tr>
						<tr>
							<td>権限：<?=$authority?></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<hr align="center" size="1" color="red" width="100%">
		<br><br>
		<div align="center">
		<table border="0">
		<!-- 変更ボタン -->
		<td><form action="../updateUser/updateUser.php" method="post">
			<input type="hidden" name="user" value="<?=$_POST['user']?>">
			<input type="submit" name="update" value="変更">
			</form>
		</td>
		<td>&emsp;</td>
		<!-- 削除ボタン -->
		<td><form action="../deleteUser/deleteUser.php" method="post">
			<input type="hidden" name="user" value="<?=$_POST['user']?>">
			<input type="submit" name="delete" value="削除">
			</form>
		</td>
		</table>
		</div>

		<br><br>
		<form action="listUser.php" method="post">
			<table align="center" width="40%">
				<tr>
					<th align="center" width="20%" bgcolor="#797979">ユーザー</th>
					<td align="center" width="20%"><?=$User->getUser()?></td>
				</tr>
				<tr>
					<th align="center" width="20%" bgcolor="#797979">パスワード</th>
					<td align="center" width="20%"><?=$User->getPassword()?></td>
				</tr>
				<tr>
					<th align="center" width="20%" bgcolor="#797979">Eメール</th>
					<td align="center" width="20%"><?=$User->getEmail()?></td>
				</tr>
				<tr>
					<th align="center" width="20%" bgcolor="#797979">権限</th>
					<td align="center" width="20%"><?=$User->getAuthority()?></td>
				</tr>
			</table>
		</form>
		<br><br><br>
		<hr align="center" size="2" color="red" width="100%">
		<table align="center" width="100%">
			<tr><td>Copyright (C) 2022 All Rights Reserved.</td></tr>
		</table>
	</body>
</html>