<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>
	<body>
	<h1>ユーザー登録</h1>
	<?php
	if(isset($_POST['insertUser'])){
	    echo "登録できた";
	}else{
	?>
	<form action ="insertUser.php" method="post">
		ユーザーID<input type="text" name="userid"><br>
		パスワード<input type="text" name="password"><br>
		メールアドレス<input type="text" name="email"><br>
		権限  <input type="radio" name="authority" value=1>無
			  <input type="radio" name="authority" value=2>有<br>
		<input type="hidden" name="insertUser">
		<input type="submit" value="送信">
	</form>
	<?php
	}
	?>
	</body>

	</html>